### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by FinlayDaG33k** [flavioaiello/swarm-router#11]
Hii there,

I'm trying to get this thing to work, but due to the lack of documentation, it has proven quite difficult so far.

This is my `swarm-router` service:
```yml
version: '3.2'
services:
  swarm-router:
    image: flavioaiello/swarm-router:latest
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
      - "8443:8443"
      - "1111:1111"
    networks:
      default:
      routing:
    deploy:
      resources:
        reservations:
          cpus: '0.5'
          memory: 128M
        limits:
          memory: 128M
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any

networks:
  default:
    driver: overlay
  routing:
    driver: overlay
    attachable: true
```

This deployment goes just fine.
Now I try to attach my app (which should be popping up when I enter `http://testing.finlaydag33k.nl` in my browser) to it using the following stack:
```yml
version: '3.7'
services:
  swarm-router:
    image: 'flavioaiello/swarm-router:latest'
    environment:
      - HTTP_PORTS=8080
      - TLS_PORTS=8443
      - DNS_BACKEND_FQDN=false
      - HTTP_BACKENDS_PORT=nginx:8080
    networks:
      default:
      swarm-router_routing:
        aliases:
          - swarm-router.testing.finlaydag33k.nl
  nginx:
    ...
    networks:
      default:
      swarm-router_routing:
        aliases:
          - testing.finlaydag33k.nl

networks:
  default:
    internal: true
    driver: overlay
  swarm-router_routing:
    external: true
```

This deploys just fine but when I go to the url `http://testing.finlaydag33k.nl` a page with the following message shows up:
```
502 Bad Gateway
The server returned an invalid or incomplete response.
```

I wonder if theres something I did wrong in my setup and how to fix it.
Some sidenotes:
- the `nginx` service does not have a `ports` section defined (as this would result in a huge mess when I try to run multiple apps using the same nginx port)
- `swarm-router_routing` is the name of the network as it shows up in `docker network ls`

I hope to hear back soon!

Cheers!
